name: Unit Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Unit Tests
      uses: cryptopirates/ta-lib@master
      with:
        gitUsername: ${{ secrets.GIT_USERNAME }}
        gitAccessToken: ${{ secrets.GIT_ACCESS_TOKEN }}
        requiresTALib: true
        requiresLibrdkafka: true
